steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/bengkel-akap", "."]
    dir: "backend"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/bengkel-akap"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - run
      - deploy
      - bengkel-akap
      - --image
      - gcr.io/$PROJECT_ID/bengkel-akap
      - --timeout
      - 1000s
      - --port
      - "8080"
      - --region
      - us-central1
      - --allow-unauthenticated
      - --set-env-vars
      - DB_HOST=${_DB_HOST},DB_NAME=${_DB_NAME},DB_PASSWORD=${_DB_PASSWORD},DB_USERNAME=${_DB_USERNAME}

options:
  logging: CLOUD_LOGGING_ONLY
